version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/app/workspace
    environment:
      - NODE_ENV=development
      - PORT=8080
      - WORKSPACE_PATH=/app/workspace
    command: npm run dev

  mcp-server-prod:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    ports:
      - "8081:8080"
    volumes:
      - ./workspace:/app/workspace
    environment:
      - NODE_ENV=production
      - PORT=8080
      - WORKSPACE_PATH=/app/workspace

  # Sandbox container for executing commands
  mcp-sandbox:
    image: node:18-alpine
    volumes:
      - ./sandbox:/workspace
    working_dir: /workspace
    # Security: Run as non-root user
    user: "1000:1000"
    # Security: No privileged access
    privileged: false
    # Security: No network access by default
    network_mode: "none"
    # Security: Read-only root filesystem
    read_only: true
    # Security: Allow writing only to specific directories
    tmpfs:
      - /tmp
    command: sleep infinity